(** Pure-unit coverage for [Tls_config.with_client_cert].

    Parses PEM bytes from [test/fixtures/mtls/{ca,client}.crt]
    and [test/fixtures/mtls/client.key] — committed self-signed
    fixtures, declared as a [(source_tree fixtures)] dep on the
    unit_tests stanza so dune copies them next to the exe. The
    test never opens a TLS connection; live mTLS against a real
    server lives in [test_mtls_integration] which keeps using
    [tls/] (runtime-generated by [scripts/gen-tls-certs.sh]).

    Scope: do the PEM decoders accept the fixtures, does the
    resulting [Tls_config.t] carry a [`Single _] client cert,
    and does a bad PEM produce a redacted error message. *)

module T = Valkey.Tls_config

(* dune runs the unit_tests binary with cwd = [_build/default/test/]
   and copies the [fixtures/] source tree next to it via the (deps)
   clause on the (test) stanza, so [fixtures/mtls/<name>] resolves
   without any path fallback. *)
let read_file path =
  let ic = open_in path in
  let len = in_channel_length ic in
  let buf = really_input_string ic len in
  close_in ic;
  buf

let fixture name = read_file ("fixtures/mtls/" ^ name)

let test_parses_valid_mtls_pair () =
  let ca_pem = fixture "ca.crt" in
  let cert_pem = fixture "client.crt" in
  let key_pem = fixture "client.key" in
  match
    T.with_client_cert ~ca_pem ~client_cert_pem:cert_pem
      ~client_key_pem:key_pem ()
  with
  | Ok t ->
      (match T.client_certificates t with
       | `None ->
           Alcotest.fail "expected `Single _ client cert, got `None"
       | `Single (chain, _key) ->
           if List.length chain < 1 then
             Alcotest.fail "expected at least one cert in chain")
  | Error m ->
      Alcotest.failf "with_client_cert rejected valid fixture: %s" m

let test_rejects_garbage_ca () =
  match
    T.with_client_cert
      ~ca_pem:"-----BEGIN CERTIFICATE-----\ngarbage\n-----END CERTIFICATE-----\n"
      ~client_cert_pem:(fixture "client.crt")
      ~client_key_pem:(fixture "client.key")
      ()
  with
  | Ok _ -> Alcotest.fail "expected parse failure"
  | Error m ->
      (* Redacted: no cert bytes, only the stage name. *)
      Alcotest.(check bool) "redacted error names the stage"
        true
        (let needle = "ca_pem" in
         let rec contains i =
           i + String.length needle <= String.length m
           && (String.sub m i (String.length needle) = needle
               || contains (i + 1))
         in
         contains 0)

let test_rejects_garbage_client_cert () =
  match
    T.with_client_cert
      ~ca_pem:(fixture "ca.crt")
      ~client_cert_pem:"not a PEM"
      ~client_key_pem:(fixture "client.key")
      ()
  with
  | Ok _ -> Alcotest.fail "expected parse failure"
  | Error m ->
      Alcotest.(check bool) "redacted error names the stage"
        true
        (let needle = "client_cert_pem" in
         let rec contains i =
           i + String.length needle <= String.length m
           && (String.sub m i (String.length needle) = needle
               || contains (i + 1))
         in
         contains 0)

let test_rejects_garbage_client_key () =
  match
    T.with_client_cert
      ~ca_pem:(fixture "ca.crt")
      ~client_cert_pem:(fixture "client.crt")
      ~client_key_pem:"not a PEM"
      ()
  with
  | Ok _ -> Alcotest.fail "expected parse failure"
  | Error m ->
      Alcotest.(check bool) "redacted error names the stage"
        true
        (let needle = "client_key_pem" in
         let rec contains i =
           i + String.length needle <= String.length m
           && (String.sub m i (String.length needle) = needle
               || contains (i + 1))
         in
         contains 0)

let test_non_mtls_constructors_have_no_client_cert () =
  (* The pre-existing constructors (insecure, with_ca_cert,
     with_system_cas) must leave client_certificates = `None
     so [wrap_with_tls] doesn't accidentally enable mTLS. *)
  let t1 = T.insecure () in
  Alcotest.(check bool) "insecure() -> no client cert"
    true (T.client_certificates t1 = `None);
  let t2 = T.with_ca_cert ~ca_pem:(fixture "ca.crt") () in
  Alcotest.(check bool) "with_ca_cert() -> no client cert"
    true (T.client_certificates t2 = `None)

let tests =
  [ Alcotest.test_case "with_client_cert parses valid PEM" `Quick
      test_parses_valid_mtls_pair;
    Alcotest.test_case "with_client_cert rejects garbage CA"
      `Quick test_rejects_garbage_ca;
    Alcotest.test_case "with_client_cert rejects garbage cert"
      `Quick test_rejects_garbage_client_cert;
    Alcotest.test_case "with_client_cert rejects garbage key"
      `Quick test_rejects_garbage_client_key;
    Alcotest.test_case "non-mTLS constructors have no client cert"
      `Quick test_non_mtls_constructors_have_no_client_cert;
  ]
